version: '3.3'

services:
  app:
    build:
      context: .
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    env_file:
      - .env
    volumes:
      - ./app/input:/input
      - ./app/output:/output
  pytorch-worker:
    build:
      context: .
      dockerfile: Dockerfile_pytorch
      args:
        ROLE: "WORKER"
  pytorch-leader:
    build:
      context: .
      dockerfile: Dockerfile_pytorch
      args:
        ROLE: "LEADER"
