from tests.constants import EXAMPLES_DIR


IMAGE_CLASSIFIER_DIR = EXAMPLES_DIR / "image_classifier"
SPLIT_DATA_PATH = IMAGE_CLASSIFIER_DIR / "split_data"
DATA_PATH = IMAGE_CLASSIFIER_DIR / "data"
MNIST_IMAGES_PATH = DATA_PATH / "MNIST/raw"

VALID_DATA_SPLIT_PARTITIONS = (2, 4, 5, 8)
