from tests.constants import ExampleDirs, TRAINED_MODEL_FILE


FINE_TUNE_LLM_PYTORCH_DIR = ExampleDirs.FINE_TUNE_LLM_PYTORCH
SPLIT_DATA_PATH = FINE_TUNE_LLM_PYTORCH_DIR / "split_data"
DATA_PATH = FINE_TUNE_LLM_PYTORCH_DIR / "data"
RAW_DATA_PATH = FINE_TUNE_LLM_PYTORCH_DIR / "raw_data"
TRAINED_MODEL_PATH = FINE_TUNE_LLM_PYTORCH_DIR / TRAINED_MODEL_FILE

VALID_DATA_SPLIT_PARTITIONS = (2, 4, 5, 8)
